name: 02-2. Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - run: echo " This job builds the configuration ${{ matrix.configuration }}."

